export { api } from './client'
export { authApi } from './auth'
export { usersApi } from './users'
export { recordsApi } from './records'
export { adminApi } from './admin'
export type { User, PatientRecord, PatientRecordCreate, AuditLog, AdminStats, ApiResponse } from './types'
